# Generated by Django 5.1.1 on 2025-06-14 10:43

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='adoptionDate',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlybox',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.R2Storage(), upload_to='boxes/'),
        ),
    ]
