# Generated by Django 5.1.1 on 2025-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dog_adoptiondate_alter_monthlybox_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_toys_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_treats_delivered',
            field=models.IntegerField(default=0),
        ),
    ]
