# Generated by Django 5.1.1 on 2025-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_total_toys_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybox',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlybox',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlybox',
            name='year',
            field=models.IntegerField(),
        ),
    ]
