# Generated by Django 5.1.1 on 2025-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_monthlybox_day_alter_monthlybox_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='skipped_months',
            field=models.IntegerField(default=0),
        ),
    ]
